import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../models/customer.dart';
import '../theme/app_colors.dart';
import '../utils/validation_utils.dart';
import '../widgets/custom_dialog.dart';

class CustomerCreationWidget extends StatefulWidget {
  final Function(Customer) onCustomerCreated;
  final Function() onCancel;
  final bool isLoading;

  const CustomerCreationWidget({
    Key? key,
    required this.onCustomerCreated,
    required this.onCancel,
    this.isLoading = false,
  }) : super(key: key);

  @override
  State<CustomerCreationWidget> createState() => _CustomerCreationWidgetState();
}

class _CustomerCreationWidgetState extends State<CustomerCreationWidget> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  
  // Controllers
  final TextEditingController _firstNameController = TextEditingController();
  final TextEditingController _lastNameController = TextEditingController();
  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _phoneController = TextEditingController();
  final TextEditingController _addressController = TextEditingController();
  final TextEditingController _cityController = TextEditingController();
  final TextEditingController _stateController = TextEditingController();
  final TextEditingController _zipCodeController = TextEditingController();
  final TextEditingController _notesController = TextEditingController();

  // Preferences
  String _preferredContactMethod = 'phone';
  bool _receivePromotions = true;
  bool _receiveReminders = true;
  String? _preferredMechanic;
  String? _preferredServiceTime;

  final List<String> _contactMethods = ['phone', 'email', 'text'];
  final List<String> _serviceTimes = ['morning', 'afternoon', 'evening'];
  final List<String> _mechanics = [
    'Any Available',
    'John Smith',
    'Mike Johnson',
    'Sarah Wilson',
    'David Brown',
  ];

  @override
  void dispose() {
    _firstNameController.dispose();
    _lastNameController.dispose();
    _emailController.dispose();
    _phoneController.dispose();
    _addressController.dispose();
    _cityController.dispose();
    _stateController.dispose();
    _zipCodeController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  void _createCustomer() {
    if (!_formKey.currentState!.validate()) return;

    final newCustomer = Customer(
      id: '', // Will be generated by Firebase
      firstName: _firstNameController.text.trim(),
      lastName: _lastNameController.text.trim(),
      email: _emailController.text.trim().toLowerCase(),
      phone: _phoneController.text.trim(),
      address: _addressController.text.trim().isEmpty
          ? null
          : _addressController.text.trim(),
      city: _cityController.text.trim().isEmpty
          ? null
          : _cityController.text.trim(),
      state: _stateController.text.trim().isEmpty
          ? null
          : _stateController.text.trim(),
      zipCode: _zipCodeController.text.trim().isEmpty
          ? null
          : _zipCodeController.text.trim(),
      createdAt: DateTime.now(),
      preferences: CustomerPreferences(
        preferredContactMethod: _preferredContactMethod,
        receivePromotions: _receivePromotions,
        receiveReminders: _receiveReminders,
        preferredMechanic: _preferredMechanic,
        preferredServiceTime: _preferredServiceTime,
      ),
      notes: _notesController.text.trim().isEmpty
          ? null
          : _notesController.text.trim(),
    );

    widget.onCustomerCreated(newCustomer);
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Section Header
          Row(
            children: [
              Icon(
                Icons.person_add,
                color: AppColors.primaryPink,
                size: 24,
              ),
              const SizedBox(width: 12),
              Text(
                'Create New Customer',
                style: GoogleFonts.poppins(
                  fontSize: 18,
                  fontWeight: FontWeight.w600,
                  color: AppColors.textPrimary,
                ),
              ),
            ],
          ),
          
          const SizedBox(height: 8),
          
          Text(
            'Enter customer information to create a new customer profile',
            style: GoogleFonts.poppins(
              fontSize: 14,
              color: AppColors.textSecondary,
            ),
          ),
          
          const SizedBox(height: 24),

          // Basic Information
          Text(
            'Basic Information',
            style: GoogleFonts.poppins(
              fontSize: 16,
              fontWeight: FontWeight.w600,
              color: AppColors.textPrimary,
            ),
          ),
          
          const SizedBox(height: 16),

          // First Name and Last Name Row
          Row(
            children: [
              Expanded(
                child: CustomTextField(
                  label: 'First Name',
                  hint: 'Enter first name',
                  controller: _firstNameController,
                  validator: (value) => ValidationUtils.validateName(value, 'First Name'),
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: CustomTextField(
                  label: 'Last Name',
                  hint: 'Enter last name',
                  controller: _lastNameController,
                  validator: (value) => ValidationUtils.validateName(value, 'Last Name'),
                ),
              ),
            ],
          ),

          const SizedBox(height: 20),

          // Phone and Email Row
          Row(
            children: [
              Expanded(
                child: CustomTextField(
                  label: 'Phone Number',
                  hint: 'e.g., (555) 123-4567',
                  controller: _phoneController,
                  keyboardType: TextInputType.phone,
                  validator: ValidationUtils.validatePhoneNumber,
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: CustomTextField(
                  label: 'Email Address',
                  hint: 'e.g., customer@email.com',
                  controller: _emailController,
                  keyboardType: TextInputType.emailAddress,
                  validator: ValidationUtils.validateEmail,
                ),
              ),
            ],
          ),

          const SizedBox(height: 24),

          // Address Information (Optional)
          Text(
            'Address Information (Optional)',
            style: GoogleFonts.poppins(
              fontSize: 16,
              fontWeight: FontWeight.w600,
              color: AppColors.textPrimary,
            ),
          ),
          
          const SizedBox(height: 16),

          // Address
          CustomTextField(
            label: 'Street Address',
            hint: 'Enter street address',
            controller: _addressController,
          ),

          const SizedBox(height: 20),

          // City, State, Zip Row
          Row(
            children: [
              Expanded(
                flex: 2,
                child: CustomTextField(
                  label: 'City',
                  hint: 'Enter city',
                  controller: _cityController,
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: CustomTextField(
                  label: 'State',
                  hint: 'State',
                  controller: _stateController,
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: CustomTextField(
                  label: 'Zip Code',
                  hint: 'Zip',
                  controller: _zipCodeController,
                  keyboardType: TextInputType.number,
                ),
              ),
            ],
          ),

          const SizedBox(height: 24),

          // Preferences
          Text(
            'Preferences',
            style: GoogleFonts.poppins(
              fontSize: 16,
              fontWeight: FontWeight.w600,
              color: AppColors.textPrimary,
            ),
          ),
          
          const SizedBox(height: 16),

          // Contact Method and Service Time Row
          Row(
            children: [
              Expanded(
                child: CustomDropdown<String>(
                  label: 'Preferred Contact',
                  value: _preferredContactMethod,
                  items: _contactMethods.map((method) {
                    return DropdownMenuItem(
                      value: method,
                      child: Text(method.toUpperCase()),
                    );
                  }).toList(),
                  onChanged: (value) {
                    setState(() {
                      _preferredContactMethod = value ?? 'phone';
                    });
                  },
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: CustomDropdown<String>(
                  label: 'Preferred Time',
                  value: _preferredServiceTime,
                  items: _serviceTimes.map((time) {
                    return DropdownMenuItem(
                      value: time,
                      child: Text(time.toUpperCase()),
                    );
                  }).toList(),
                  onChanged: (value) {
                    setState(() {
                      _preferredServiceTime = value;
                    });
                  },
                ),
              ),
            ],
          ),

          const SizedBox(height: 20),

          // Preferred Mechanic
          CustomDropdown<String>(
            label: 'Preferred Mechanic',
            value: _preferredMechanic,
            items: _mechanics.map((mechanic) {
              return DropdownMenuItem(
                value: mechanic,
                child: Text(mechanic),
              );
            }).toList(),
            onChanged: (value) {
              setState(() {
                _preferredMechanic = value;
              });
            },
          ),

          const SizedBox(height: 20),

          // Checkboxes
          Row(
            children: [
              Expanded(
                child: CheckboxListTile(
                  title: Text(
                    'Receive Promotions',
                    style: GoogleFonts.poppins(fontSize: 14),
                  ),
                  value: _receivePromotions,
                  onChanged: (value) {
                    setState(() {
                      _receivePromotions = value ?? true;
                    });
                  },
                  activeColor: AppColors.primaryPink,
                  contentPadding: EdgeInsets.zero,
                ),
              ),
              Expanded(
                child: CheckboxListTile(
                  title: Text(
                    'Receive Reminders',
                    style: GoogleFonts.poppins(fontSize: 14),
                  ),
                  value: _receiveReminders,
                  onChanged: (value) {
                    setState(() {
                      _receiveReminders = value ?? true;
                    });
                  },
                  activeColor: AppColors.primaryPink,
                  contentPadding: EdgeInsets.zero,
                ),
              ),
            ],
          ),

          const SizedBox(height: 20),

          // Notes
          CustomTextField(
            label: 'Notes (Optional)',
            hint: 'Any additional notes about the customer...',
            controller: _notesController,
            maxLines: 3,
          ),

          const SizedBox(height: 32),

          // Action Buttons
          Row(
            children: [
              Expanded(
                child: OutlinedButton(
                  onPressed: widget.isLoading ? null : widget.onCancel,
                  style: OutlinedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    side: BorderSide(color: AppColors.textSecondary),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: Text(
                    'Cancel',
                    style: GoogleFonts.poppins(
                      fontSize: 16,
                      fontWeight: FontWeight.w500,
                      color: AppColors.textSecondary,
                    ),
                  ),
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: ElevatedButton(
                  onPressed: widget.isLoading ? null : _createCustomer,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.primaryPink,
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: widget.isLoading
                      ? SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                          ),
                        )
                      : Text(
                          'Create Customer',
                          style: GoogleFonts.poppins(
                            fontSize: 16,
                            fontWeight: FontWeight.w600,
                            color: Colors.white,
                          ),
                        ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
